{
  type:  {
    provider: "aws",
    region: "ap-southeast-2"
  },
  input: {
  # raw_path - absolute path that defines the csv file location that were exported from the iPhone
    raw_path: '/Users/ntonthat/Library/Mobile Documents/iCloud~com~ifunography~HealthExport/Documents/raw/'
  },
  output: {
  # output_local - absolute path that defines the local storage to output to
    output_local: "/Users/ntonthat/Documents/scratch/apple-health-calendar/outputs",
  # output_cal defines the public storage to output to after it has been output locally
    output_cal: "s3://ntonthat-ahc"
  },
  col_map: {
        'Date': 'date',
        'Apple Exercise Time (min)': "exercise_mins",
        'Carbohydrates (g)': 'carbs',
        'Mindful Minutes (min)': "mindful_mins",
        'Protein (g)': 'protein',
        'Total Fat (g)': 'fat',
        'Sleep Analysis [In Bed] (hr)': 'sleep_in_bed',
        'Sleep Analysis [Asleep] (hr)': 'sleep_asleep',
        'Step Count (count)': 'steps',
        'Weight & Body Mass (kg) ': 'weight'
  }
}