[tool.poetry]
name = "apple-health-calendar"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "apple_health_calendar"}]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.5.0"

[tool.poetry.group.dev.dependencies]
pandas = "^1.5.0"
ics = "^0.7.2"
logging = "^0.4.9.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
