[tool.poetry]
name = "apple-health-calendar"
version = "0.1.0"
description = ""
authors = ["Nam Tonthat <n.nam.tonthat@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.16"
pandas = "^1.5.0"
ics = "^0.7.2"
logging = "^0.4.9.6"
pyarrow = "^10.0.1"
fsspec = "^2023.1.0"
dvc = { extras = ["s3"], version = "^2.43.1" }
pydantic = "^1.10.4"
pandasql = "^0.7.3"
s3fs = "^2023.1.0"
fastparquet = "^2023.1.0"
flask = "^2.2.2"
werkzeug = "^2.2.2"
aiobotocore = "^2.4.2"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
