service: layer-pandas-numpy

package:
  patterns:
    - "!node_modules/**"

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-2

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: python-numpy
      description: "Layer which contains pandas and numpy library"
      compatibleRuntimes:
        - python3.9
    slim: true
    slimPatterns:
      - "**/*.egg-info*"
