carbohydrates:
  name: carbohydrates
  units: g
  emoticon: 🍞
  group: macros
total_fat:
  name: fats
  units: g
  emoticon: 🧁
  group: macros
protein:
  name: protein
  units: g
  emoticon: 🍗
  group: macros
fiber:
  name: fibre
  units: g
  emoticon: 🥦
  group: macros
sleep_analysis_asleep:
  name: asleep
  emoticon: 🌒
  group: sleep
sleep_analysis_inBed:
  name: in bed
  emoticon: 🛏️
  group: sleep
sleep_analysis_sleepStart:
  name: bedtime
  emoticon: 💤
  group: sleep_times
step_count:
  name: steps
  emoticon: 👣
  units: steps
  group: dailys
mindful_minutes:
  name: meditation
  units: mins
  emoticon: 🧘‍♂️
  group: dailys
apple_exercise_time:
  name: exercise
  units: mins
  emoticon: 🚲
  group: dailys
weight_body_mass:
  name: weight
  units: kg
  emoticon: 🐻
  group: dailys
