service: apple-health

package:
  patterns:
    - "!node_modules/**"
    - "!venv/**"
    - "!__pycache__/**"
  excludeDevDependencies: true

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-2
  memorySize: 128
  timeout: 30
  apiGateway:
    shouldStartNameWithService: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join: ["", [Fn::GetAtt: [MyBucket, Arn]]]
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join: ["", [Fn::GetAtt: [MyBucket, Arn], "/*"]]

resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: "ntonthat-apple-health-data"

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  healthlake:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"

  parse_parquet:
    handler: parse_parquet.run
    layers:
      - arn:aws:lambda:ap-southeast-2:110386608476:layer:python-numpy:10
    events:
      - s3:
          bucket: "ntonthat-apple-health-data"
          event: s3:ObjectCreated:*
          rules:
            - prefix: syncs/
            - suffix: .json
          existing: true

  create_calendar:
    handler: create_calendar.run
    layers:
      - arn:aws:lambda:ap-southeast-2:110386608476:layer:python-numpy:10
    package:
      patterns:
        - config/mapping.json
        - config/latest_data.sql
    events:
      - s3:
          bucket: "ntonthat-apple-health-data"
          event: s3:ObjectCreated:*
          rules:
            - prefix: parquets/
            - suffix: .parquet
          existing: true
custom:
  wsgi:
    app: healthlake.app
    dockerizePip: true
    slim: true
    slimPatterns:
      - "**/*.egg-info*"
