service: apple-health

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-2
  memorySize: 128
  timeout: 30
  apiGateway:
    shouldStartNameWithService: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join: ["", [Fn::GetAtt: [MyBucket, Arn]]]
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join: ["", [Fn::GetAtt: [MyBucket, Arn], "/*"]]

plugins:
  - serverless-wsgi
  - serverless-python-requirements
resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: "ntonthat-apple-health-data"

functions:
  healthlake:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"

  parse_as_parquet:
    handler: parse_as_parquet.handler
    events:
      - s3:
        bucket: s3:ObjectCreated:*
        rules:
          - prefix: sync/
          - suffix: .json

custom:
  wsgi:
    app: healthlake.app
  pythonRequirements:
    dockerizePip: "false"
